from ._compat import reraise as reraise
from typing import Any

class PactBase:
    def __init__(self, timeout_seconds: Any) -> None: ...
    def get_timeout_exception(self, exc_info: Any) -> None: ...
    def is_finished(self) -> bool: ...
    def poll(self) -> bool: ...
    def then(self, callback: Any, *args: Any, **kwargs: Any) -> "PactBase": ...
    def lastly(self, callback: Any, *args: Any, **kwargs: Any) -> "PactBase": ...
    def during(self, callback: Any, *args: Any, **kwargs: Any) -> "PactBase": ...
    def on_timeout(self, callback: Any, *args: Any, **kwargs: Any) -> "PactBase": ...
    def wait(self, **kwargs: Any) -> None: ...
