from .base import PactBase as PactBase
from typing import Any, Optional

class PactGroup(PactBase):
    def __init__(self, pacts: Optional[Any] = ..., lazy: bool = ..., timeout_seconds: Optional[Any] = ...) -> None: ...
    def __iadd__(self, other: Any) -> "PactGroup": ...
    def __iter__(self) -> Any: ...
    def get_timeout_exception(self, exc_info: Any) -> Any: ...
    def add(self, pact: Any, absorb: bool = ...) -> None: ...
