from .base import PactBase as PactBase
from .group import PactGroup as PactGroup
from .utils import EdgeTriggered as EdgeTriggered
from typing import Any, Optional

class Pact(PactBase):
    msg: Any = ...
    def __init__(self, msg: Any, timeout_seconds: Optional[Any] = ..., lazy: bool = ...) -> None: ...
    def until(self, predicate: Any, *args: Any, **kwargs: Any) -> "Pact": ...
    def group_with(self, other: Any) -> "PactGroup": ...
    def __add__(self, other: Any) -> "Pact": ...
