from typing import Any
from types import ModuleType


class NoInitFileFound(Exception): ...

def import_file(filename: Any) -> ModuleType: ...
def set_package_name(directory: Any, name: Any) -> None: ...
