from collections import namedtuple
from typing import Any


_StrCandidate = namedtuple('StrCandidate', ['weight', 'unit', 'str', 'unit_name'])

class Capacity:
    bits: Any = ...
    def __init__(self, bits: Any) -> None: ...
    def __nonzero__(self): ...
    def __bool__(self): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __abs__(self): ...
    def __neg__(self): ...
    def __mul__(self, other: Any): ...
    __rmul__: Any = ...
    def __add__(self, other: Any): ...
    __radd__: Any = ...
    def __sub__(self, other: Any): ...
    def __rsub__(self, other: Any): ...
    def __div__(self, other: Any): ...
    def __truediv__(self, other: Any): ...
    def __floordiv__(self, other: Any): ...
    def __rdiv__(self, other: Any): ...
    __rtruediv__: Any = ...
    __rfloordiv__: Any = ...
    def __mod__(self, other: Any): ...
    def __rmod__(self, other: Any): ...
    def roundup(self, boundary: Any): ...
    def rounddown(self, boundary: Any): ...
    def __format__(self, capacity: Any): ...


def from_string(s: str) -> Capacity:
    ...


EB: Capacity
EiB: Capacity
GB: Capacity
GiB: Capacity
KB: Capacity
KiB: Capacity
MB: Capacity
MiB: Capacity
PB: Capacity
PiB: Capacity
TB: Capacity
TiB: Capacity
bit: Capacity
byte: Capacity
