from typing import Any

class Deadline:
    def is_expired(self) -> None: ...
    def get_num_seconds_remaining(self) -> None: ...

class Within(Deadline):
    def __init__(self, seconds: Any) -> None: ...
    def is_expired(self): ...
    def get_num_seconds_remaining(self): ...

class Whenever(Deadline):
    def is_expired(self): ...

def make_deadline(seconds: Any): ...
