name: CI
on: [push]
jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python_version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install requirements
        run: pip install -e . -r tests/requirements.txt pylint
      - name: Check with pylint
        run: pylint -j $(nproc) scottypy tests
